name: Build and Release Electron Application

on:
  push:
    branches:
      - master
      - develop
      - 'feature/design'
  pull_request:
    types:
      - opened
      - synchronize
  release:
    types:
      - published

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.16.1

      - name: Install dependencies
        run: npm ci

      - name: Build Windows
        run: npm run buildWindows

  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.16.1

      - name: Install dependencies
        run: npm ci

      - name: Build Linux
        run: npm run buildLinux

  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.16.1

      - name: Install dependencies
        run: npm ci

      - name: Build macOS
        run: npm run buildMac

  create-release:
    needs: [build-windows, build-linux, build-macos]
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/feature/design' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.16.1

      - name: Get package info
        id: package_info
        run: echo "::set-output name=version::$(node -p "require('./package.json').version")"

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          tag_name: v${{ steps.package_info.outputs.version }}
          release_name: |
            ${{ github.ref != 'refs/heads/master' && github.ref != 'refs/heads/develop' && github.ref != 'refs/heads/feature/design' }}Pre-release ${{ steps.package_info.outputs.version }}
          body: |
            ${{ github.ref != 'refs/heads/master' && github.ref != 'refs/heads/develop' && github.ref != 'refs/heads/feature/design' }}Pre-release ${{ steps.package_info.outputs.version }} |
          draft: false
          prerelease: ${{ github.ref != 'refs/heads/master' }}

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: |
            ./dist/denki-classics-${{ steps.package_info.outputs.version }}.exe,
            ./dist/denki-classics-${{ steps.package_info.outputs.version }}.AppImage,
            ./dist/denki-classics-${{ steps.package_info.outputs.version }}.pkg
          asset_name: |
            denki-classics-${{ steps.package_info.outputs.version }}.exe,
            denki-classics-${{ steps.package_info.outputs.version }}.AppImage,
            denki-classics-${{ steps.package_info.outputs.version }}.pkg
          asset_content_type: application/octet-stream
