name: Build and Test Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        include:
          - os: windows-latest
            buildScript: buildWindows
            releaseFileExtension: .exe
          - os: ubuntu-latest
            buildScript: buildLinux
            releaseFileExtension: .AppImage
          - os: macos-latest
            buildScript: buildMac
            releaseFileExtension: .pkg

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get Node.js version
        id: get_node_version
        run: |
          node_version=$(cat .node-version 2>/dev/null || cat .nvmrc 2>/dev/null)
          node_version="${node_version//v/}" # Remove 'v' prefix if present
          echo "::set-output name=node_version::$node_version"

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version:  ${{ steps.get_node_version.outputs.node_version }}

      - name: Install dependencies
        run: npm ci

      - name: Build Electron application
        run: npm run ${{ matrix.buildScript }}
